// Liste des indicatifs pays pour les formulaires
export const countryCodes = [
  { code: "+93", pays: "Afghanistan" },
  { code: "+355", pays: "Albanie" },
  { code: "+213", pays: "Algerie" },
  { code: "+1", pays: "Etats-Unis" },
  { code: "+376", pays: "Andorre" },
  { code: "+244", pays: "Angola" },
  { code: "+1", pays: "Antigua-et-Barbuda" },
  { code: "+966", pays: "Arabie Saoudite" },
  { code: "+32", pays: "Belgique" },
  { code: "+229", pays: "Benin" },
  { code: "+1", pays: "Canada" },
  { code: "+236", pays: "Centrafrique" },
  { code: "+56", pays: "Chili" },
  { code: "+86", pays: "Chine" },
  { code: "+357", pays: "Chypre" },
  { code: "+225", pays: "Cote d'Ivoire" },
  { code: "+385", pays: "Croatie" },
  { code: "+45", pays: "Danemark" },
  { code: "+20", pays: "Egypte" },
  { code: "+971", pays: "Emirats Arabes Unis" },
  { code: "+34", pays: "Espagne" },
  { code: "+372", pays: "Estonie" },
  { code: "+251", pays: "Ethiopie" },
  { code: "+358", pays: "Finlande" },
  { code: "+33", pays: "France" },
  { code: "+995", pays: "Georgie" },
  { code: "+233", pays: "Ghana" },
  { code: "+350", pays: "Gibraltar" },
  { code: "+30", pays: "Grece" },
  { code: "+240", pays: "Guinee equatoriale" },
  { code: "+592", pays: "Guyana" },
  { code: "+509", pays: "Haiti" },
  { code: "+36", pays: "Hongrie" },
  { code: "+91", pays: "Inde" },
  { code: "+62", pays: "Indonesie" },
  { code: "+964", pays: "Irak" },
  { code: "+98", pays: "Iran" },
  { code: "+353", pays: "Irlande" },
  { code: "+972", pays: "Israel" },
  { code: "+39", pays: "Italie" },
  { code: "+81", pays: "Japon" },
  { code: "+254", pays: "Kenya" },
  { code: "+996", pays: "Kirghizistan" },
  { code: "+856", pays: "Laos" },
  { code: "+266", pays: "Lesotho" },
  { code: "+371", pays: "Lettonie" },
  { code: "+218", pays: "Libye" },
  { code: "+423", pays: "Liechtenstein" },
  { code: "+370", pays: "Lituanie" },
  { code: "+352", pays: "Luxembourg" },
  { code: "+853", pays: "Macao" },
  { code: "+389", pays: "Macedoine" },
  { code: "+261", pays: "Madagascar" },
  { code: "+60", pays: "Malaisie" },
  { code: "+223", pays: "Mali" },
  { code: "+356", pays: "Malte" },
  { code: "+212", pays: "Maroc" },
  { code: "+377", pays: "Monaco" },
  { code: "+976", pays: "Mongolie" },
  { code: "+382", pays: "Montenegro" },
  { code: "+95", pays: "Myanmar" },
  { code: "+264", pays: "Namibie" },
  { code: "+977", pays: "Nepal" },
  { code: "+31", pays: "Pays-Bas" },
  { code: "+234", pays: "Nigeria" },
  { code: "+47", pays: "Norvege" },
  { code: "+968", pays: "Oman" },
  { code: "+92", pays: "Pakistan" },
  { code: "+507", pays: "Panama" },
  { code: "+51", pays: "Perou" },
  { code: "+63", pays: "Philippines" },
  { code: "+48", pays: "Pologne" },
  { code: "+351", pays: "Portugal" },
  { code: "+1", pays: "Puerto Rico" },
  { code: "+974", pays: "Qatar" },
  { code: "+262", pays: "Reunion" },
  { code: "+40", pays: "Roumanie" },
  { code: "+7", pays: "Russie" },
  { code: "+250", pays: "Rwanda" },
  { code: "+1", pays: "Saint-Christophe-et-Nieves" },
  { code: "+1", pays: "Sainte-Lucie" },
  { code: "+1", pays: "Saint-Vincent-et-les-Grenadines" },
  { code: "+378", pays: "Saint-Marin" },
  { code: "+221", pays: "Senegal" },
  { code: "+248", pays: "Seychelles" },
  { code: "+232", pays: "Sierra Leone" },
  { code: "+65", pays: "Singapour" },
  { code: "+421", pays: "Slovaquie" },
  { code: "+386", pays: "Slovenie" },
  { code: "+252", pays: "Somalie" },
  { code: "+27", pays: "Afrique du Sud" },
  { code: "+82", pays: "Coree du Sud" },
  { code: "+94", pays: "Sri Lanka" },
  { code: "+249", pays: "Soudan" },
  { code: "+46", pays: "Suede" },
  { code: "+41", pays: "Suisse" },
  { code: "+963", pays: "Syrie" },
  { code: "+992", pays: "Tadjikistan" },
  { code: "+66", pays: "Thailande" },
  { code: "+228", pays: "Togo" },
  { code: "+216", pays: "Tunisie" },
  { code: "+993", pays: "Turkmenistan" },
  { code: "+90", pays: "Turquie" },
  { code: "+1", pays: "Iles Vierges americaines" },
  { code: "+380", pays: "Ukraine" },
  { code: "+44", pays: "Royaume-Uni" },
  { code: "+58", pays: "Venezuela" },
  { code: "+84", pays: "Vietnam" },
  { code: "+260", pays: "Zambie" },
  { code: "+263", pays: "Zimbabwe" },
];

// Liste des nationalités pour les formulaires
export const nationalities = [
  "Afghanistan", "Afrique du Sud", "Albanie", "Allemagne", "Algerie",
  "Argentine", "Australie", "Autriche", "Belgique", "Bresil",
  "Bulgarie", "Canada", "Chili", "Chine", "Colombie",
  "Coree du Sud", "Cote d'Ivoire", "Croatie", "Danemark", "Egypte",
  "Emirats Arabes Unis", "Espagne", "Estonie", "Etats-Unis", "Ethiopie",
  "Finlande", "France", "Gabon", "Grece", "Hongrie",
  "Inde", "Indonesie", "Irak", "Iran", "Irlande",
  "Israel", "Italie", "Japon", "Jordanie", "Kenya",
  "Liban", "Libye", "Luxembourg", "Malaisie", "Mali",
  "Maroc", "Mexique", "Monaco", "Norvege", "Nouvelle-Zelande",
  "Pakistan", "Pays-Bas", "Perou", "Pologne", "Portugal",
  "Qatar", "Roumanie", "Royaume-Uni", "Russie", "Senegal",
  "Serbie", "Singapour", "Slovaquie", "Slovenie", "Suede",
  "Suisse", "Syrie", "Tunisie", "Turquie", "Ukraine",
  "Venezuela", "Vietnam"
];
